#!/bin/bash
set -e

msg() {
  echo -e "\e[1;32m$*\e[0m"
}

find . -name \*.yml -print0 | xargs -0 yamllint -s
msg Success: yamllint passed

jekyll build -t --config _config.yml,_dev.yml
msg Success: Built jekyll site

jekyll serve --skip-initial-build --detach
msg Success: Serving jekyll site locally

/usr/gem/bin/htmlproofer \
  --assume-extension \
  --log-level=debug \
  --http-status-ignore 429 \
  --url-ignore https://twitter.com/TheLocehiliosan \
  _site
msg Success: Validated site with html-proofer
