#!/usr/bin/env bash

# yadm - Yet Another Dotfiles Manager
# Copyright (C) 2015-2019 Tim Byrne and Martin Zuther

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

YADM_CHECKSUMS="$YADM_HOOK_DIR/files.checksums"


# is current directory on yadm's work path?
# (adapted from https://unix.stackexchange.com/a/6438/122163)
if [ "${PWD##$YADM_HOOK_WORK}" != "$PWD" ]; then
    ON_WORK_PATH=1
else
    ON_WORK_PATH=0
fi


# list all files or only those in the subdirectories below?
OPTION_LIST_ALL=0
for argument in ${YADM_HOOK_FULL_COMMAND[*]}; do
    # mimick git ls-files by displaying all files when not on work
    # path
    if [ "$argument" = "-a" ] || [ $ON_WORK_PATH -eq 0 ]; then
        OPTION_LIST_ALL=1
        break
    fi
done


# if there is no checksum file, exit with original status of yadm
# command
if [ ! -f "$YADM_CHECKSUMS" ]; then
    exit "$YADM_HOOK_EXIT"
fi

# list encrypted files; try to satisfy the "list -a" argument and
# beautify the output (requires "grep" and "sed")
if command -v grep > /dev/null && command -v sed > /dev/null; then
    # remove checksums from file names
    while IFS= read -r filename; do
        if [ $OPTION_LIST_ALL -eq 0 ]; then
            # list only files in the subdirectories below (i.e. files
            # whose relative path doesn't begin with "../")
            REL_PATH=$(relative_path "$PWD" "$YADM_HOOK_WORK/$filename")

            if ! echo "$REL_PATH" | grep '^\.\./' > /dev/null; then
               echo "$REL_PATH"
            fi
        else
            # list all files
            echo "$filename"
        fi
    done <<< "$(sed -r 's/^\S+\s+//' "$YADM_CHECKSUMS")"
else
    # just display checksum file
    cat "$YADM_CHECKSUMS"
fi

# return original exit status of yadm command
exit "$YADM_HOOK_EXIT"
